package com.company.ngos.common.enums;

public enum ApplicationStatus {

    APPLICATION_CREATED,

    DOCUMENT_VERIFICATION_PENDING,
    DOCUMENT_VERIFICATION_FAILED,
    DOCUMENT_VERIFIED,

    BUREAU_CHECK_PENDING,
    BUREAU_CHECK_FAILED,
    BUREAU_CHECK_COMPLETED,

    OFFER_GENERATED,
    OFFER_CONFIRMED,

    PROCESSING,
    DISPATCHED,

    REJECTED,
    CANCELLED
}
